### PR TITLE
point to new remote apk source

### PR DESCRIPTION
**Pull request by yazninja**

### CODE REVIEW

**Comment by cryptofyre** [comment]
versioning's a little strange shouldn't it be 0.3.2? Android might be pissy.

**Comment by yazninja** [comment]
> versioning's a little strange shouldn't it be 0.3.2? Android might be pissy.

its fine "-b1" is treated as prerelease version so it'll know its 0.3.0

**Comment by yazninja** [comment]
pls merge these now

**Comment by yazninja** [comment]
ok pls merge this now

**Review by cryptofyre — APPROVED** [review]

**Pull request merged**
